# Generated by Django 4.1.7 on 2023-03-22 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='contenido',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='search',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='search',
            name='resumen',
            field=models.TextField(default=''),
        ),
    ]
